name: .NET publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish-action:
  
    runs-on: windows-latest
  
    steps:
    - run: |
        echo "Release tag: ${{ github.ref }}"
    - run: |
        echo "Release triggered by event: ${{ github.event_name }}"
    - run: |
        echo "Running on: ${{ runner.os }}"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -p:PublishProfile=FolderProfile
    - name: "Build Changelog for Release"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        outputFile: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release on github
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/Release/net7.0-windows/publish/win-x64/BroDisplaySetup.exe
          LICENSE.md
          CHANGELOG.md
        tag_name: ${{ github.ref_name }}
        body: |
          # ${{steps.github_release.outputs.repo}} ${{ github.ref_name }}
          
          ## Changelog
          ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
